RONDB-123: Change company name "Logical Clocks AB" -> "Hopsworks AB"
- Change company name from "Logical Clocks AB" and variants to
  "Hopsworks AB" in copyright notices, comments, documentation, code
  etc. except for links to github.
- Rename `lc_scripts/` to `hopsworks_scripts/`.
- Update `hopsworks_scripts/config_git` with the new company name.
- Add `.mailmap` file to change how @logicalclocks.com email addresses
  are displayed in historical commits.

diff --git a/hopsworks_scripts/config_git b/hopsworks_scripts/config_git
--- a/hopsworks_scripts/config_git
+++ b/hopsworks_scripts/config_git
@@ -1,5 +1,5 @@
 #!/bin/bash
-# Copyright (c) 2021, 2022, Logical Clocks and/or its affiliates.
+# Copyright (c) 2021, 2022, Hopsworks AB and/or its affiliates.
 
 set -e
 
@@ -20,7 +20,7 @@ mkscript() {
     echo
 }
 
-mkscript .git/hooks/pre-commit "A hook to check copyright for Logical Clocks" <<"EOF"
+mkscript .git/hooks/pre-commit "A hook to check copyright for Hopsworks AB" <<"EOF"
 #!/bin/bash
 set -e
 year=`date +%Y`
@@ -42,13 +42,13 @@ git diff --cached --name-only --diff-filter=d |
                 tac;
         } |
             # Check that a correct copyright notice is present
-            grep -Eq '^[ #*-]*Copyright (\(c\)|\\\(co) ('"$(seq -s '|' 2020 $year)), $year, "'Logical Clocks and\/or its affiliates\.$' ||
+            grep -Eq '^[ #*-]*Copyright (\(c\)|\\\(co) ('"$(seq -s '|' 2020 $year)), $year, "'Hopsworks AB and\/or its affiliates\.$' ||
             # If not, fail with instructions
             {
                 echo "$filename:";
-                echo "  Can't find a correct copyright notice for Logical Clocks.";
+                echo "  Can't find a correct copyright notice for Hopsworks AB.";
                 echo "  If one exists, correct it, otherwise add the following to the header comment:";
-                echo "   Copyright (c) $year, $year, Logical Clocks and/or its affiliates.";
+                echo "   Copyright (c) $year, $year, Hopsworks AB and/or its affiliates.";
                 exitcode=1;
             }
         done
@@ -60,10 +60,10 @@ git config merge.conflictstyle diff3
 echo This repository is now configured to use the diff3 merge conflictstyle
 echo ""
 
-git config user.email | grep -Eq "@logicalclocks\.com$" || {
-    echo Warning: Git is not configured to identify you as an employee of Logical Clocks.
+git config user.email | grep -Eq "@hopsworks\.ai$" || {
+    echo Warning: Git is not configured to identify you as an employee of Hopsworks AB.
     echo You can do so by running:
     echo "    git config --global user.name 'Firstname Lastname'"
-    echo "    git config --global user.email yourname@logicalclocks.com"
+    echo "    git config --global user.email yourname@hopsworks.ai"
     echo
 }
